# Generated by Django 5.1.4 on 2024-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
